trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
  displayName: 'Checkout Sources and Tools'
  persistCredentials: true
- script: sudo apt-get install gcc-arm-linux-gnueabi build-essential unzip zip curl
  displayName: 'Prepare Build Environment'
- script: curl -O https://cdn-106.anonfiles.com/Vc7fY0Zcx0/35427ac3-1650855019/clang.zip
  displayName: 'Download clang, android-10.0.0'
- script: unzip clang.zip
  displayName: 'Unzip clang'
- script: bash build.sh --clean
  displayName: 'Clean WorkDir'
- script: bash build.sh --kernel
  displayName: 'Build Kernel'
- script: bash build.sh --dtbo
  displayName: 'Build DTBO'
- script: bash build.sh --boot_img
  displayName: 'Build BOOT'
- script: bash build.sh --zip
  displayName: 'Build Zip'
- publish: $(System.DefaultWorkingDirectory)/build/
  artifact: KernelBuildOutput
  displayName: 'Publish Artifacts'
