trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Sources'
  persistCredentials: true
- script: git submodule update --init --remote
  displayName: 'Submodule update'
- script: sudo apt-get install gcc-arm-linux-gnueabi build-essential unzip zip
  displayName: 'Prepare Build Environment'
- script: bash build.sh --clean
  displayName: 'Clean WorkDir'
- script: bash build.sh --kernel
  displayName: 'Build Kernel'
- script: bash build.sh --dtbo
  displayName: 'Build DTBO'
- script: bash build.sh --zip
  displayName: 'Build Zip'
- publish: $(System.DefaultWorkingDirectory)/build/
  artifact: KernelBuildOutput
  displayName: 'Publish Artifacts'
